# Generated by Django 5.0.1 on 2024-01-13 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmeFormation', models.CharField(max_length=30)),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('hierarchie', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=50)),
                ('diplome', models.CharField(max_length=70)),
                ('telephone', models.CharField(max_length=30)),
                ('adresse', models.CharField(max_length=80)),
                ('dateNaissance', models.DateField()),
                ('salaire', models.FloatField()),
                ('service', models.CharField(max_length=80)),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('nomComplet', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=100)),
                ('motPass', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Inscriptions_Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.formation')),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocument', models.CharField(max_length=30)),
                ('typeDocument', models.CharField(max_length=30)),
                ('dateEnregistrement', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeconges', models.CharField(max_length=50)),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField()),
                ('etatAvancement', models.FloatField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSanction', models.CharField(max_length=30)),
                ('dateSanction', models.DateField()),
                ('explication', models.TextField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.AddField(
            model_name='personnel',
            name='utilisateur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.utilisateur'),
        ),
    ]
