# Generated by Django 5.0.1 on 2024-02-03 01:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('programmeFormation', models.CharField(max_length=30)),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('matricule', models.CharField(max_length=50)),
                ('sexe', models.CharField(max_length=50)),
                ('hierarchie', models.CharField(max_length=50)),
                ('fonction', models.CharField(max_length=80)),
                ('grade', models.CharField(max_length=50)),
                ('diplome', models.FileField(upload_to='diplome_personnel')),
                ('telephone', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=80)),
                ('dateNaissance', models.DateField()),
                ('lieuNaissace', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='Image_Profil_Personnel')),
                ('salaire', models.FloatField()),
                ('service', models.CharField(max_length=80)),
                ('observation', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(max_length=50)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.formation')),
            ],
        ),
        migrations.AddField(
            model_name='formation',
            name='personnel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomDocument', models.CharField(max_length=30)),
                ('typeDocument', models.CharField(max_length=30)),
                ('dateEnregistrement', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeconges', models.CharField(max_length=50)),
                ('dateDeb', models.DateField()),
                ('dateFin', models.DateField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Sanction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeSanction', models.CharField(max_length=30)),
                ('dateSanction', models.DateField()),
                ('explication', models.TextField()),
                ('personnel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('poste', models.CharField(max_length=100)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
