# Generated by Django 5.0.1 on 2024-01-22 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscriptions_Formation',
        ),
    ]
