# Generated by Django 5.0.1 on 2024-01-23 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_delete_inscriptions_formation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='nomComplet',
            new_name='prenom',
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='poste',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
