# Generated by Django 5.0.1 on 2024-01-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_rename_nomcomplet_utilisateur_prenom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='adresse',
        ),
        migrations.AddField(
            model_name='personnel',
            name='email',
            field=models.EmailField(default=1, max_length=80),
            preserve_default=False,
        ),
    ]
