# Generated by Django 5.0.1 on 2024-01-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_remove_personnel_adresse_personnel_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personnel',
            name='utilisateur',
        ),
        migrations.AddField(
            model_name='personnel',
            name='prenom',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
