# Generated by Django 5.0.1 on 2024-01-28 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0005_remove_personnel_utilisateur_personnel_prenom'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='photo',
            field=models.ImageField(default=1, upload_to='Image_Profil_Personnel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='personnel',
            name='diplome',
            field=models.FileField(upload_to='diplome_personnel'),
        ),
    ]
