# Generated by Django 5.0.1 on 2024-01-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_personnel_photo_alter_personnel_diplome'),
    ]

    operations = [
        migrations.AddField(
            model_name='personnel',
            name='lieuNaissace',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
